hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d-%H-%M-%S}
model:
  ffm:
    mode: linear
    L: 10
    num_input: 3
  mlp:
    num_inputs: 60
    num_outputs: 3
    num_neurons: 256
    depth: 16
    skip_list: [2,5,8,11,14]
    body_acti: LeakyReLU
    last_acti: Sigmoid
  nerf:
    type: GIFNERF

gif:
  data_path: data/test.gif
  ofargs: [0.5, 3, 15, 3, 5, 1.2, 0]
train:
  train_split: 3
  batch_size: 3000
  GPUIndex: [0]
  optim:
    type: Adam
    kwargs:
      lr: 1e-3
      weight_decay: 1e-8
  lr_sche:
    type: ExponentialLR
    kwargs:
      gamma: 0.99
  ckpt: Null
  num_epoches: 500