hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d-%H-%M-%S}
model:
  ffm:
    mode: linear
    L: 10
    num_input: 3
  mlp:
    num_inputs: 60
    num_outputs: 3
    num_neurons: 256
    depth: 8
    skip_list: [2,4]
    body_acti: LeakyReLU
    last_acti: Null
  nerf:
    type: GIFNERF

gif:
  data_path: data/doll3.gif
  ofargs: [0.5, 3, 15, 3, 5, 1.2, 0]
train:
  stra_size: 3
  train_split: 1
  target_fps_factor: 5
  batch_size: 150000
  GPUIndex: [0]
  optim:
    type: Adam
    kwargs:
      lr: 1e-3
      weight_decay: 1e-8
  lr_sche:
    type: ExponentialLR
    kwargs:
      gamma: 0.999
  ckpt: /home/zihao/Desktop/workspace/outputs/2022-04-15-21-29-12/ckpts/epoch29.pt
  num_epoches: 300